### ISSUE TITLE
Exception when using incorrect login details.

### ISSUE THREAD

**Issue by Nibbler999** [leeroybrun/node-fibaro-api#2]
Connecting using incorrect username/password throws an error:

``` javascript
ReferenceError: TokenError is not defined
    at new AuthError (/home/nibbler/node-fibaro-api/lib/fibaro.js:165:3)
    at Request._callback (/home/nibbler/node-fibaro-api/lib/fibaro.js:48:30)
    at Request.self.callback (/home/nibbler/node-fibaro-api/node_modules/request/request.js:237:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/nibbler/node-fibaro-api/node_modules/request/request.js:1146:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/nibbler/node-fibaro-api/node_modules/request/request.js:1097:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:938:16
    at process._tickCallback (node.js:419:13)
```

**Comment by leeroybrun** [comment]
It should be fixed now. Can you try again with this fix ?

**Comment by Nibbler999** [comment]
That fixes the exception, thanks.
